services:
  postgres:
    image: 'postgres:16-alpine' # 'latest' yerine versiyon belirtmek Best Practice'dir
    container_name: omniticket_db
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5432:5432' # Bilgisayarındaki 5432'yi konteynerdaki 5432'ye bağladık
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: 'redis:7.4-alpine'
    container_name: omniticket_redis
    ports:
      - '6379:6379' # Redis portunu dışarı açtık

volumes:
  pgdata: # Verilerin silinmemesi için disk alanı ayırdık
